version: '3.2'
services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        restart: always

    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        hostname: monitoring
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 9100:9100
        restart: always

    blackbox-exporter:
      image: prom/blackbox-exporter
      ports:
        - 9115:9115
      restart: always
      volumes:
        - ./blackbox:/config
      command: --config.file=/config/blackbox.yml

    grafana:
        image: grafana/grafana
        user: "0:0"
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - ./grafana/data:/var/lib/grafana
        restart: always

    alertmanager-bot:
        command:
        - --alertmanager.url=http://alertmanager:9093
        - --log.level=info
        - --store=bolt
        - --bolt.path=/data/bot.db
        environment:
          TELEGRAM_ADMIN: "${TELEGRAM_ADMIN}"
          TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
        image: metalmatze/alertmanager-bot:0.4.3
        ports:
        - 8080:8080
        restart: always
        user: "0:0"
        volumes:
        - ./data:/data

    alertmanager:
      image: prom/alertmanager:v0.21.0
      user: "0:0"
      ports:
        - 9093:9093
      volumes:
        - ./alertmanager/:/etc/alertmanager/
      restart: always
      command:
        - '--config.file=/etc/alertmanager/config.yml'
        - '--storage.path=/etc/alertmanager/data'
